version: '3.9'

services:
  db:
    image: postgres:18
    restart: always
    container_name: medicos-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: medicos